# First steps into Pytorch
for more details: https://pytorch.org/docs/stable/index.html

In [2]:
#Let's start by importing the library
import torch

In [3]:
# Generate a Tensor of size 2x2x4
t = torch.Tensor(2,2,4)
t_2 = torch.Tensor(16,32,128,128)
t_3 = torch.Tensor(1, 3, 256, 256)
# .size() allows to get the size of the tensor
print(t.size(), t_2.size(), t_3.size())

torch.Size([2, 2, 4]) torch.Size([16, 32, 128, 128]) torch.Size([1, 3, 256, 256])


In [4]:
# Generate a tensor filled with random numbers 
# from a normal distribution with mean 0 and variance 1 
# with the same size
t_r = torch.randn(2,2,4)
# and a tensor filled with ones
t_ones = torch.ones(2,2,4)
t_zeros = torch.zeros(2,2,4)

In [5]:
# Print the tensors
print(t,"\n", t_r,"\n", t_ones,"\n", t_zeros)

tensor([[[-6.2382e+26,  9.3887e-43,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]],

        [[ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00,  0.0000e+00]]]) 
 tensor([[[ 0.4928,  1.0169, -1.4192, -0.6406],
         [ 1.6055, -0.0688,  1.3662,  1.7347]],

        [[-0.5077, -0.9950, -0.1137, -1.4051],
         [-0.0354, -0.4517, -1.8992, -0.4640]]]) 
 tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]]) 
 tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [6]:
# To resize a tensor do
#t_r.resize_(4,4)
#print(t_r.size(), t_r)
t_r.resize_(16,16)
print(t_r.size())
# be CAREFULL with in-place operations like this one
# since they will permanently change the tensor

torch.Size([16, 16])


In [7]:
# It is better to firstly clone the tensor and then resize it
t_c = t.clone()
t_c.resize_(2,2)
# so that the original one remains untouched
print(t.size(), t_c.size())

torch.Size([2, 2, 4]) torch.Size([2, 2])


In [8]:
# An alternative is to use the .view() operator which do not alter the total number of dimensions of the tensor
t_v = torch.randn(4,4)
t_v1 = t_v.view(2,2,4)
print(t_v.size(), t_v1.size())
t_v2 = t_v.view(16)

torch.Size([4, 4]) torch.Size([2, 2, 4])


In [9]:
# Fill a tensor with a specific number
t_ones.fill_(3)
print(t_ones)
t_ones.fill_(64)
print(t_ones)

tensor([[[3., 3., 3., 3.],
         [3., 3., 3., 3.]],

        [[3., 3., 3., 3.],
         [3., 3., 3., 3.]]])
tensor([[[64., 64., 64., 64.],
         [64., 64., 64., 64.]],

        [[64., 64., 64., 64.],
         [64., 64., 64., 64.]]])


In [10]:
# If you want to create a tensor filled with specific numbers just do
v = torch.Tensor([7,8,9])
print(v)
print(v.size())

tensor([7., 8., 9.])
torch.Size([3])


Working with tensors is exactly like working with vectors and matrices!

In [11]:
w = torch.Tensor([3,2,1]) # a vector
# Sum (or subtraction)
print(w + v)
# Element-wise multiplication (or division)
print(w * v)
# Square all elements in the tensor
w2 = w.pow(2)
print(w2)
# and so on...

tensor([10., 10., 10.])
tensor([21., 16.,  9.])
tensor([9., 4., 1.])


In [12]:
# tensors need to have the same number of dimensions in order for them to be summed
q = torch.randn(2,4,2)
p = torch.randn(2,3,2)

print(q + p)

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

In [13]:
# Define a 2x4 matrix
m = torch.Tensor([[1,2,3,4],
                 [5,6,7,8]])
print(m)
print(m.size(), m.size(0), m.size(1))

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
torch.Size([2, 4]) 2 4


In [14]:
# Get a value from the matrix
print(m[1,2])
# Get a column
print(m[:,2])
# Get a row
print(m[1, :])
# Getting an intervall of values
print(m[:, 2:])
print(m[:, :2])

tensor(7.)
tensor([3., 7.])
tensor([5., 6., 7., 8.])
tensor([[3., 4.],
        [7., 8.]])
tensor([[1., 2.],
        [5., 6.]])


In [15]:
# like with vectors you can do
# Sum (or subtraction)
b = torch.randn(2,4)
print(m + b)
# Multiplication (or division)
print(m * b)

tensor([[1.4296, 2.5601, 2.6682, 2.4832],
        [2.9184, 5.1618, 6.5185, 8.6409]])
tensor([[  0.4296,   1.1202,  -0.9955,  -6.0673],
        [-10.4078,  -5.0292,  -3.3702,   5.1273]])


In [16]:
# Transpose a matrix
print(m.t())

tensor([[1., 5.],
        [2., 6.],
        [3., 7.],
        [4., 8.]])


In [20]:
# Flatten a tensor maintaining the same batch size (the first element of the Tensor)
m_4_dim = torch.randn(4,8,2,2)
print(m_4_dim.view(m_4_dim.size(0), -1).size()) 
# Rearrange dimensions
print(m_4_dim.view(m_4_dim.size(0), 16, 2).size())

torch.Size([4, 32])
torch.Size([4, 16, 2])


Moving tensors to GPU

In [ ]:
# Move tensor to GPU device 0 if there is one (first GPU in the system)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
m_d = m.to(device)
print(device)
print(m_d.device)
m = m.cpu()
print(m.device)
m = m.cuda()
print(m.device)

cpu
cpu
cpu


AssertionError: Torch not compiled with CUDA enabled

Moving tensors to Numpy

In [ ]:
# Converts tensor to numpy array
m_np = m.cpu().numpy()
print(m_np)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Tensors concatenations

In [ ]:
a = torch.Tensor([[1, 2, 3, 4]]) # 1,4
b = torch.Tensor([[5, 6, 7, 8]]) # 1,4

# Concatenate on axis 0 -> 2,4
print(torch.cat((a, b), 0))
# Concatenate on axis 1 -> 1,8
print(torch.cat((a, b), 1))

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])


In [ ]:
c = torch.randn(3,4)
d = torch.randn(3,12)

print(torch.cat((c,d), 1)) # 3, 16

tensor([[-0.5761,  0.0488, -0.3192, -1.2819, -1.1903, -1.2653, -0.4413,  0.0115,
         -0.2928, -0.0687, -0.2429, -1.2225,  0.1313, -0.0505,  0.7516,  1.2403],
        [-0.0964,  0.5224, -0.2119, -0.8346, -0.0508, -1.1016, -1.7592,  0.3400,
         -1.9827,  1.3682, -1.5947,  0.0943, -0.8750, -0.3777,  0.6877, -1.3687],
        [ 1.1269, -1.9267, -0.8574, -1.7598,  0.5188,  1.0428,  0.6802,  0.4081,
          2.0929,  1.1952, -0.2497,  1.4201,  1.6200, -0.7374, -0.7212, -1.4813]])


In [ ]:
# Adding and removing dimensions from Tensor
r_t = torch.randn(3,64,64)

# add a dimension
r_t = r_t.unsqueeze(0) # argument is WHERE we want the dimension to be added
print(r_t.size())

# remove a dimension
r_t = r_t.squeeze(0) # argument is WHERE we want the dimension to be removed
print(r_t.size())

torch.Size([1, 3, 64, 64])
torch.Size([3, 64, 64])


In [ ]:
# Ex1: Split a 3 dimensional tensor of dimension 4x64x128 
# into 2 tensors of size 4x32x128
# and then concatenate them together to get the original size back
x = torch.randn(4,64,128)
x_1 = x[:,0:32,:]
x_2 = x[:,32:,:]
x_new = torch.cat((x_1,x_2),1)

if torch.equal(x, x_new) :
    print("ok!")
else :
    print("not ok!")

ok!


In [ ]:
# Ex2: You have two matrices of dimension: 4x256x4 and 4x16x64 
# concatenate them together to form a single matrix
# of dimension 4x64x32
y_1 = torch.randn(4,256,4)
y_2 = torch.randn(4,16,64)

y_1 = y_1.reshape(4,32,32)
y_2 = y_2.reshape(4,32,32)
y = torch.cat((y_1, y_2), 1)
print(y.size())

torch.Size([4, 64, 32])


In [ ]:
# Ex3: You have 4 matrixes representing 4 RGB images of dimension 3x128x128.
# Create a grid of dimension 3x256x256
z_1 = torch.randn(3,128,128)
z_2 = torch.randn(3,128,128)
z_3 = torch.randn(3,128,128)
z_4 = torch.randn(3,128,128)

z_12 = torch.cat((z_1,z_2), 1)
z_34 = torch.cat((z_3,z_4), 1)

z = torch.cat((z_12,z_34), 2)
print(z.size())

torch.Size([3, 256, 256])
