# First steps into Pytorch
for more details: https://pytorch.org/docs/stable/index.html

In [129]:
#Let's start by importing the library
import torch

A <code>torch.Tensor</code> is a multi-dimensional matrix containing elements of a single data type.

In [130]:
# Generate a Tensor of size 2x2x4
t = torch.Tensor(2,2,4)
t_2 = torch.Tensor(16,32,128,128)
t_3 = torch.Tensor(1, 3, 256, 256)
# .size() allows to get the size of the tensor
print(t.size(), t_2.size(), t_3.size())

torch.Size([2, 2, 4]) torch.Size([16, 32, 128, 128]) torch.Size([1, 3, 256, 256])


In [131]:
# Generate a tensor filled with random numbers 
# from a normal distribution with mean 0 and variance 1 
# with the same size
t_r = torch.randn(2,2,4)
# and a tensor filled with ones
t_ones = torch.ones(2,2,4)
t_zeros = torch.zeros(2,2,4)

In [132]:
# Print the tensors
print(t, t_r, t_ones, t_zeros)

tensor([[[1.6793e+07, 1.8301e-42, 1.4013e-45, 0.0000e+00],
         [1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00]],

        [[1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00],
         [1.4013e-45, 0.0000e+00, 1.4013e-45, 0.0000e+00]]]) tensor([[[ 0.3661,  0.0303, -1.1051,  0.3882],
         [ 0.6697, -0.2072,  0.9561, -1.6525]],

        [[ 0.6290,  0.3042, -2.1273,  0.7153],
         [-0.1040,  0.8442,  0.2390, -0.3282]]]) tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.]]]) tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.]]])


In [133]:
# To resize a tensor do
#t_r.resize_(4,4)
#print(t_r.size(), t_r)
t_r.resize_(16,16)
print(t_r.size())
# be CAREFULL with in-place operations like this one
# since they will permanently change the tensor

torch.Size([16, 16])


In [134]:
# It is better to firstly clone the tensor and then resize it
t_c = t.clone()
t_c.resize_(2,2)
# so that the original one remains untouched
print(t.size(), t_c.size())

torch.Size([2, 2, 4]) torch.Size([2, 2])


In [135]:
# An alternative is to use the .view() operator which do not alter the total number of dimensions of the tensor
t_v = torch.randn(4,4)
t_v1 = t_v.view(2,2,4)
print(t_v.size(), t_v1.size())
t_v2 = t_v.view(16,1)

torch.Size([4, 4]) torch.Size([2, 2, 4])


In [136]:
# Fill a tensor with a specific number
t_ones.fill_(3)
print(t_ones)
t_ones.fill_(64)
print(t_ones)

tensor([[[3., 3., 3., 3.],
         [3., 3., 3., 3.]],

        [[3., 3., 3., 3.],
         [3., 3., 3., 3.]]])
tensor([[[64., 64., 64., 64.],
         [64., 64., 64., 64.]],

        [[64., 64., 64., 64.],
         [64., 64., 64., 64.]]])


In [137]:
# If you want to create a tensor filled with specific numbers just do
v = torch.Tensor([7,8,9])
print(v)
print(v.size())

tensor([7., 8., 9.])
torch.Size([3])


Working with tensors is exactly like working with vectors and matrices!

In [138]:
w = torch.Tensor([3,2,1]) # a vector
# Sum (or subtraction)
print(w + v)
# Element-wise multiplication (or division)
print(w * v)
# Square all elements in the tensor
w2 = w.pow(2)
print(w2)
# and so on...

tensor([10., 10., 10.])
tensor([21., 16.,  9.])
tensor([9., 4., 1.])


In [139]:
# tensors need to have the same number of dimensions in order for them to be summed
q = torch.randn(2,4,2)
p = torch.randn(2,3,2)

print(q + p)

RuntimeError: The size of tensor a (4) must match the size of tensor b (3) at non-singleton dimension 1

In [140]:
# Define a 2x4 matrix
m = torch.Tensor([[1,2,3,4],
                 [5,6,7,8]])
print(m)
print(m.size(), m.size(0), m.size(1))

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
torch.Size([2, 4]) 2 4


In [141]:
# Get a value from the matrix
print(m)
print(m[1,2])
# Get a column
print(m[:,2])
# Get a row
print(m[1, :])
# Getting an intervall of values
print(m[:, 2:])
print(m[:, :2])

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
tensor(7.)
tensor([3., 7.])
tensor([5., 6., 7., 8.])
tensor([[3., 4.],
        [7., 8.]])
tensor([[1., 2.],
        [5., 6.]])


In [142]:
# like with vectors you can do
# Sum (or subtraction)
b = torch.randn(2,4)
print(m + b)
# Multiplication (or division)
print(m * b)

tensor([[1.6556, 1.9312, 2.6410, 3.1352],
        [5.2667, 6.0399, 5.9178, 9.3629]])
tensor([[ 0.6556, -0.1376, -1.0771, -3.4591],
        [ 1.3337,  0.2392, -7.5751, 10.9031]])


In [143]:
# Transpose a matrix
print(m)
print(m.t())

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
tensor([[1., 5.],
        [2., 6.],
        [3., 7.],
        [4., 8.]])


In [144]:
# Flatten a tensor maintaining the same batch size (the first element of the Tensor)
m_4_dim = torch.randn(4,8,2,2)
print(m_4_dim.view(m_4_dim.size(0), -1).size()) 
# Rearrange dimensions
print(m_4_dim.view(m_4_dim.size(0), 16, 2).size()) 

torch.Size([4, 32])
torch.Size([4, 16, 2])


Moving tensors to GPU

In [145]:
# Move tensor to GPU device 0 if there is one (first GPU in the system)
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
m_d = m.to(device)
print(device)
print(m_d.device)

m = m.cpu()
print(m.device)
m = m.cuda()
print(m.device)

cpu
cpu
cpu


AssertionError: Torch not compiled with CUDA enabled

Moving tensors to Numpy

In [146]:
# Converts tensor to numpy array
m_np = m.cpu().numpy()
print(m_np)

[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


Tensors concatenations

In [147]:
a = torch.Tensor([[1, 2, 3, 4]]) # 1,4
b = torch.Tensor([[5, 6, 7, 8]]) # 1,4

# Concatenate on axis 0 -> 2,4
print(torch.cat((a, b), 0))
# Concatenate on axis 1 -> 1,8
print(torch.cat((a, b), 1))

tensor([[1., 2., 3., 4.],
        [5., 6., 7., 8.]])
tensor([[1., 2., 3., 4., 5., 6., 7., 8.]])


In [148]:
c = torch.randn(3,4)
d = torch.randn(3,12)

print(torch.cat((c,d), 1)) # 3, 16

tensor([[ 0.2544, -0.5177, -0.0775,  0.4854, -0.0535,  0.9260,  0.7800,  1.0172,
         -0.7976, -1.6298, -0.3121,  0.6684,  1.8589,  0.3541,  0.7289,  0.2047],
        [ 0.2683, -0.8013,  0.5218,  0.2909,  0.7020, -1.1730, -0.6764, -0.0503,
         -0.9779,  1.2578,  1.8571, -0.4359, -0.0529, -1.2444,  1.0015,  1.1683],
        [ 0.1283,  0.0710,  0.3746,  0.9810,  0.7084,  0.3485, -0.1654, -0.0023,
         -0.6563,  0.8029,  0.1208, -0.9041, -1.3386,  0.4159,  0.7068,  0.8141]])


In [149]:
# Adding and removing dimensions from Tensor
r_t = torch.randn(3,64,64)
print(r_t.size())

# add a dimension
r_t = r_t.unsqueeze(0) # argument is WHERE we want the dimension to be added
print(r_t.size())

# remove a dimension
r_t = r_t.squeeze(0) # argument is WHERE we want the dimension to be removed
print(r_t.size())

torch.Size([3, 64, 64])
torch.Size([1, 3, 64, 64])
torch.Size([3, 64, 64])


In [150]:
# Ex1: Split a 3 dimensional tensor of dimension 4x64x128 
# into 2 tensors of size 4x32x128
# and then concatenate them together to get the original size back

In [151]:
test_1 = torch.randn(4,64,128) # a torch.randn(1,1,1) tensor is obviously a three dimensional tensor anyway 

test_1_1 = test_1[:,:32,:]
print(test_1_1.size())
test_1_2 = test_1[:,32:,:]
print(test_1_2.size())

test_2 = torch.cat((test_1_1, test_1_2), 1)
print(test_2.size())


torch.Size([4, 32, 128])
torch.Size([4, 32, 128])
torch.Size([4, 64, 128])


In [152]:
# Ex2: You have two matrices of dimension: 4x256x4 and 4x16x64 
# concatenate them together to form a single matrix
# of dimension 4x64x32

matrix_1 = torch.randn(4,256,4)
matrix_2 = torch.randn(4,16,64)

matrix_1 = matrix_1.resize(4,64,16)
matrix_2 = matrix_2.resize(4,64,16)
matrix_cat = torch.cat((matrix_1, matrix_2), 1)
matrix_cat = torch.cat((matrix_1, matrix_2), 2)
print(matrix_cat.size())

torch.Size([4, 64, 32])


C:\Users\bacco\AppData\Roaming\Python\Python312\site-packages\torch\_tensor.py:868: UserWarning: non-inplace resize is deprecated
  warnings.warn("non-inplace resize is deprecated")


In [153]:
# Ex3: You have 4 matrixes representing 4 RGB images of dimension 3x128x128.
# Create a grid of dimension 3x256x256

image_1 = torch.randn(3,128,128)
image_2 = torch.randn(3,128,128)
image_3 = torch.randn(3,128,128)
image_4 = torch.randn(3,128,128)

grid_1 = torch.cat((image_1, image_2), 2)
grid_2 = torch.cat((image_3, image_4), 2)
grid = torch.cat((grid_1, grid_2), 1)
print(grid.size())



torch.Size([3, 256, 256])
